ALTER TABLE "WebsiteBrief"
  ADD COLUMN IF NOT EXISTS "offerData" JSONB,
  ADD COLUMN IF NOT EXISTS "estimatedValue" DECIMAL(12, 2),
  ADD COLUMN IF NOT EXISTS "offerSentAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "offerEmailSentAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "offerWhatsappSentAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

