import React from "react";
import { Document, Font, Image, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import path from "node:path";
import type { WebOfferData } from "@/lib/web-offer";
import { webOfferTotals } from "@/lib/web-offer";
import { ACCOUNTING_LOGO_DATA_URI } from "@/lib/accounting/logo";

const fontPath = path.join(process.cwd(), "public", "fonts", "Geist-Regular.ttf");
Font.register({ family: "Geist", fonts: [{ src: fontPath, fontWeight: 400 }, { src: fontPath, fontWeight: 700 }] });

const NAVY = "#0b1b48";
const BLUE = "#245bd6";
const PALE = "#f4f7fb";
const LINE = "#d9e2ef";
const TEXT = "#263653";
const MUTED = "#66758e";

const s = StyleSheet.create({
  page: { paddingTop: 42, paddingHorizontal: 44, paddingBottom: 38, fontFamily: "Geist", fontSize: 9, color: TEXT, backgroundColor: "#fff" },
  header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  brand: { flexDirection: "row", alignItems: "center", gap: 9 }, logo: { width: 37, height: 37, objectFit: "contain" },
  brandName: { fontSize: 16, fontWeight: 700, color: NAVY, letterSpacing: 0.6 }, brandSub: { marginTop: 3, color: MUTED, fontSize: 6.8, letterSpacing: 1.5 },
  contractHead: { alignItems: "flex-end" }, contractTitle: { color: BLUE, fontSize: 15, fontWeight: 700 }, contractMeta: { marginTop: 7, fontSize: 8, fontWeight: 700 },
  topLine: { height: 3, borderRadius: 2, backgroundColor: BLUE, marginTop: 17, marginBottom: 16 },
  hero: { backgroundColor: NAVY, borderRadius: 10, padding: 23, color: "#fff", marginBottom: 19 }, kicker: { color: "#8db9ff", fontSize: 7.5, fontWeight: 700, letterSpacing: 1.6 }, heroTitle: { marginTop: 11, fontSize: 20, fontWeight: 700 }, heroText: { marginTop: 8, color: "#d9e7ff", fontSize: 9 },
  partyRow: { flexDirection: "row", gap: 11, marginBottom: 19 }, party: { width: "50%", backgroundColor: PALE, borderWidth: 1, borderColor: LINE, borderRadius: 8, padding: 14, minHeight: 112 }, label: { color: BLUE, fontSize: 7.5, fontWeight: 700, letterSpacing: 1 }, partyName: { color: "#172238", fontSize: 11.5, fontWeight: 700, marginTop: 11, marginBottom: 7 }, detail: { fontSize: 8.2, lineHeight: 1.55 }, detailStrong: { fontWeight: 700 },
  section: { marginBottom: 16 }, sectionTitle: { color: BLUE, fontSize: 11, fontWeight: 700, letterSpacing: 1.2, marginBottom: 10 }, legalBox: { borderLeftWidth: 3, borderLeftColor: BLUE, paddingLeft: 10 }, paragraph: { fontSize: 8.5, lineHeight: 1.55, textAlign: "justify", marginBottom: 7 }, bullet: { flexDirection: "row", gap: 6, marginTop: 6 }, check: { width: 12, height: 12, borderRadius: 6, backgroundColor: "#e5edff", color: BLUE, textAlign: "center", fontSize: 7, fontWeight: 700, lineHeight: 1.5 }, bulletText: { flex: 1, fontSize: 8.2, lineHeight: 1.45 },
  table: { borderWidth: 1, borderColor: LINE }, tableHead: { flexDirection: "row", backgroundColor: "#111a2e", color: "#fff", fontWeight: 700, paddingVertical: 8, paddingHorizontal: 6 }, tableRow: { flexDirection: "row", alignItems: "center", paddingVertical: 8, paddingHorizontal: 6, borderTopWidth: 1, borderTopColor: LINE }, colNr: { width: "6%" }, colService: { width: "52%" }, colQty: { width: "14%", textAlign: "right" }, colPrice: { width: "14%", textAlign: "right" }, colTotal: { width: "14%", textAlign: "right" }, itemTitle: { fontWeight: 700, color: "#172238" }, itemDetail: { marginTop: 3, color: MUTED, fontSize: 7 }, totals: { alignItems: "flex-end", backgroundColor: PALE, padding: 8 }, totalRow: { width: "46%", flexDirection: "row", justifyContent: "space-between", paddingVertical: 3 }, grandTotal: { width: "46%", flexDirection: "row", justifyContent: "space-between", backgroundColor: "#dce7ff", color: BLUE, fontWeight: 700, padding: 8, marginTop: 3 },
  conditionRow: { flexDirection: "row", gap: 9, marginBottom: 22 }, condition: { width: "33.333%", backgroundColor: PALE, borderRadius: 8, padding: 12, minHeight: 78 }, conditionLabel: { color: BLUE, fontSize: 7, fontWeight: 700, letterSpacing: 0.8, marginBottom: 8 }, conditionText: { color: "#172238", fontSize: 8.3, fontWeight: 700, lineHeight: 1.4 },
  obligations: { flexDirection: "row", gap: 22 }, obligation: { width: "50%" }, obligationTitle: { fontWeight: 700, marginBottom: 7, fontSize: 9 },
  signatures: { flexDirection: "row", gap: 16, marginTop: 23 }, signature: { width: "50%", minHeight: 128, borderWidth: 1, borderColor: "#c8d5e6", borderStyle: "dashed", borderRadius: 8, backgroundColor: "#fbfcfe", padding: 12 }, signatureFor: { fontWeight: 700, color: "#172238" }, signatureName: { marginTop: 8, color: BLUE, fontWeight: 700, fontSize: 10 }, signatureLine: { marginTop: 48, borderTopWidth: 1, borderTopColor: "#9fb0c5", paddingTop: 7, color: MUTED, fontSize: 7.5 },
  footer: { position: "absolute", bottom: 20, left: 44, right: 44, textAlign: "right", color: "#8ba0bc", fontSize: 7 },
});

function dateRo(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleDateString("ro-RO"); }
function money(value: number) { return value.toLocaleString("ro-RO", { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }
function PartyDetail({ label, value }: { label: string; value?: string }) { return value ? <Text style={s.detail}><Text style={s.detailStrong}>{label}: </Text>{value}</Text> : null; }
function Bullet({ children }: { children: React.ReactNode }) { return <View style={s.bullet}><Text style={s.check}>✓</Text><Text style={s.bulletText}>{children}</Text></View>; }
function PageFooter({ number }: { number: number }) { return <Text fixed style={s.footer}>Pagina {number} din 2</Text>; }

export function WebContractPdf({ data }: { data: WebOfferData }) {
  const totals = webOfferTotals(data);
  return <Document title={`Contract ${data.contractNumber}`} author="NEXT LEVEL AUTOMATION SRL">
    <Page size="A4" style={s.page}>
      <View style={s.header}><View style={s.brand}><Image src={ACCOUNTING_LOGO_DATA_URI} style={s.logo}/><View><Text style={s.brandName}>NEXT LEVEL</Text><Text style={s.brandSub}>AUTOMATION SRL</Text></View></View><View style={s.contractHead}><Text style={s.contractTitle}>CONTRACT PRESTĂRI SERVICII</Text><Text style={s.contractMeta}>Nr. {data.contractNumber || "_____"} / Data: {dateRo(data.contractDate)}</Text></View></View>
      <View style={s.topLine}/><View style={s.hero}><Text style={s.kicker}>STRATEGIE · DESIGN · DEZVOLTARE</Text><Text style={s.heroTitle}>{data.projectTitle}</Text><Text style={s.heroText}>Acord legal privind serviciile de dezvoltare și implementare a soluției web.</Text></View>
      <View style={s.partyRow}><View style={s.party}><Text style={s.label}>PRESTATOR</Text><Text style={s.partyName}>NEXT LEVEL AUTOMATION SRL</Text><PartyDetail label="CUI" value="55476878"/><PartyDetail label="Sediul" value="Com. Mirșid, Str. Fundăturii, Nr. 1A, Jud. Sălaj"/><PartyDetail label="Reprezentant" value="Administrator"/></View><View style={s.party}><Text style={s.label}>BENEFICIAR</Text><Text style={s.partyName}>{data.customerCompany || data.customerName || "________________"}</Text><PartyDetail label="CUI" value={data.customerCui}/><PartyDetail label="J" value={data.customerRegCom}/><PartyDetail label="Sediul" value={data.customerAddress}/><PartyDetail label="Contact" value={[data.customerPhone, data.customerEmail].filter(Boolean).join(" / ")}/><PartyDetail label="Reprezentant" value={data.customerRepresentative}/></View></View>
      <View style={s.section}><Text style={s.sectionTitle}>I. OBIECTUL CONTRACTULUI ȘI LIVRABILE</Text><View style={s.legalBox}><Text style={s.paragraph}>Prezentul contract reglementează prestarea de către Prestator în favoarea Beneficiarului a serviciilor de design și dezvoltare pentru proiectul „{data.projectTitle}”. Soluția va fi realizată conform ofertei comerciale {data.offerNumber} și cerințelor aprobate de părți.</Text><Text style={[s.paragraph,{fontWeight:700}]}>Livrabilele și serviciile incluse:</Text>{data.included.filter(Boolean).map((item,index)=><Bullet key={index}>{item}</Bullet>)}</View></View>
      <View style={s.section}><Text style={s.sectionTitle}>II. INVESTIȚIA PROPUSĂ ȘI STRUCTURA DE PREȚ</Text><View style={s.table}><View style={s.tableHead}><Text style={s.colNr}>#</Text><Text style={s.colService}>Serviciu</Text><Text style={s.colQty}>Cant.</Text><Text style={s.colPrice}>Preț unitar</Text><Text style={s.colTotal}>Total</Text></View>{data.items.map((item,index)=><View key={item.id} style={s.tableRow}><Text style={s.colNr}>{index+1}</Text><View style={s.colService}><Text style={s.itemTitle}>{item.description}</Text>{item.details ? <Text style={s.itemDetail}>{item.details}</Text> : null}</View><Text style={s.colQty}>{item.quantity} {item.unit}</Text><Text style={s.colPrice}>{money(item.unitPrice)} RON</Text><Text style={s.colTotal}>{money(item.quantity*item.unitPrice)} RON</Text></View>)}<View style={s.totals}><View style={s.totalRow}><Text>Subtotal:</Text><Text>{money(totals.net)} RON</Text></View><View style={s.totalRow}><Text>TVA ({data.vatRate}%):</Text><Text>{money(totals.vat)} RON</Text></View><View style={s.grandTotal}><Text>TOTAL INVESTIȚIE:</Text><Text>{money(totals.gross)} RON</Text></View></View></View></View>
      <PageFooter number={1}/>
    </Page>
    <Page size="A4" style={s.page}>
      <View style={s.section}><Text style={s.sectionTitle}>III. CONDIȚII COMERCIALE</Text><View style={s.conditionRow}><View style={s.condition}><Text style={s.conditionLabel}>VALABILITATE OFERTĂ</Text><Text style={s.conditionText}>{data.validity}</Text></View><View style={s.condition}><Text style={s.conditionLabel}>TERMEN EXECUȚIE</Text><Text style={s.conditionText}>{data.deliveryTerm}</Text></View><View style={s.condition}><Text style={s.conditionLabel}>STRUCTURĂ DE PLATĂ</Text><Text style={s.conditionText}>{data.paymentTerms}</Text></View></View></View>
      <View style={s.section}><Text style={s.sectionTitle}>IV. OBLIGAȚIILE PĂRȚILOR</Text><View style={s.obligations}><View style={s.obligation}><Text style={s.obligationTitle}>Prestatorul se obligă:</Text><Bullet>Să respecte specificațiile tehnice și termenul de execuție agreat.</Bullet><Bullet>Să asigure funcționalitatea soluției și instruirea asumată la predare.</Bullet><Bullet>Să informeze Beneficiarul cu privire la progres și eventualele impedimente.</Bullet></View><View style={s.obligation}><Text style={s.obligationTitle}>Beneficiarul se obligă:</Text><Bullet>Să furnizeze materialele necesare (texte, imagini și identitate vizuală) în timp util.</Bullet><Bullet>Să acorde feedback în termene rezonabile, de maximum 3 zile lucrătoare pentru fiecare revizie.</Bullet><Bullet>Să achite tranșele de plată la termenele specificate.</Bullet></View></View></View>
      <View style={s.section}><Text style={s.sectionTitle}>V. PROPRIETATE INTELECTUALĂ ȘI DISPOZIȚII FINALE</Text><View style={s.legalBox}><Text style={s.paragraph}>După achitarea integrală a facturilor aferente prezentului contract, drepturile patrimoniale asupra codului, graficii și elementelor realizate specific pentru proiect sunt transferate Beneficiarului. Licențele, modulele, fonturile, imaginile și serviciile furnizate de terți rămân supuse termenilor titularilor lor.</Text><Text style={s.paragraph}>Părțile se obligă să păstreze confidențialitatea datelor de autentificare și a informațiilor sensibile obținute pe parcursul colaborării. Prestatorul va prelucra datele personale numai în măsura necesară executării contractului.</Text><Text style={s.paragraph}>Contractul poate înceta prin acordul părților, prin notificare scrisă cu 30 de zile înainte sau de drept în caz de neexecutare culpabilă a obligațiilor, dacă situația nu este remediată într-un termen rezonabil după notificare. Eventualele litigii vor fi soluționate amiabil sau de instanțele competente.</Text><Text style={s.paragraph}>Prezentul contract, împreună cu oferta comercială {data.offerNumber}, reprezintă acordul părților și poate fi semnat olograf sau electronic, în exemplare cu aceeași valoare juridică.</Text></View></View>
      {data.notes ? <View style={s.section}><Text style={s.sectionTitle}>VI. OBSERVAȚII SPECIFICE PROIECTULUI</Text><View style={s.legalBox}><Text style={s.paragraph}>{data.notes}</Text></View></View> : null}
      <View style={s.signatures}><View style={s.signature}><Text style={s.signatureFor}>Pentru PRESTATOR,</Text><Text style={s.signatureName}>NEXT LEVEL AUTOMATION SRL</Text><Text style={s.signatureLine}>Semnătura și ștampila</Text></View><View style={s.signature}><Text style={s.signatureFor}>Pentru BENEFICIAR,</Text><Text style={s.signatureName}>{data.customerCompany || data.customerName || "________________"}</Text><Text style={s.signatureLine}>Nume: {data.customerRepresentative || "________________"}{"\n"}Semnătura și ștampila</Text></View></View>
      <PageFooter number={2}/>
    </Page>
  </Document>;
}
