"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, CheckCircle2, Circle, Clock3, FileText, Flag, Plus, Trash2, Users } from "lucide-react";
import { useToast } from "@/app/components/ui/toast";

export type InternalCalendarItemData = {
  id:string; title:string; notes:string|null; type:string; priority:string; status:string; startAt:string; endAt:string|null; allDay:boolean;
  author:{id:string;name:string}; assignee:{id:string;name:string}|null;
};
type Member={id:string;name:string};
const MONTHS=["Ianuarie","Februarie","Martie","Aprilie","Mai","Iunie","Iulie","August","Septembrie","Octombrie","Noiembrie","Decembrie"];
const DAYS=["Lu","Ma","Mi","Jo","Vi","Sâ","Du"];
const TYPE_LABELS:Record<string,string>={NOTE:"Notiță",TASK:"Task",MEETING:"Ședință",DEADLINE:"Deadline"};
const TYPE_COLORS:Record<string,string>={NOTE:"border-sky-300 bg-sky-50 text-sky-700",TASK:"border-indigo-300 bg-indigo-50 text-indigo-700",MEETING:"border-emerald-300 bg-emerald-50 text-emerald-700",DEADLINE:"border-rose-300 bg-rose-50 text-rose-700"};
function key(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function monthDays(anchor:Date){const first=new Date(anchor.getFullYear(),anchor.getMonth(),1),last=new Date(anchor.getFullYear(),anchor.getMonth()+1,0),start=new Date(first),end=new Date(last);start.setDate(start.getDate()-((start.getDay()+6)%7));end.setDate(end.getDate()+(6-((end.getDay()+6)%7)));const out:Date[]=[];for(const d=new Date(start);d<=end;d.setDate(d.getDate()+1))out.push(new Date(d));return out}

export function InternalTeamCalendar({initialItems,members,currentUserId,anchorDate}:{initialItems:InternalCalendarItemData[];members:Member[];currentUserId:string;anchorDate:string}){
  const router=useRouter(),toast=useToast(),anchor=new Date(anchorDate);
  const [showForm,setShowForm]=useState(false),[selected,setSelected]=useState(key(anchor)),[filter,setFilter]=useState("OPEN"),[mine,setMine]=useState(false),[saving,setSaving]=useState(false);
  const [form,setForm]=useState({title:"",notes:"",type:"NOTE",priority:"MEDIUM",date:key(anchor),time:"09:00",allDay:false,assigneeId:""});
  const visible=useMemo(()=>initialItems.filter(i=>(filter==="ALL"||(filter==="OPEN"?i.status!=="DONE":i.type===filter))&&(!mine||i.assignee?.id===currentUserId||i.author.id===currentUserId)),[initialItems,filter,mine,currentUserId]);
  const grouped=useMemo(()=>{const map=new Map<string,InternalCalendarItemData[]>();visible.forEach(i=>{const k=key(new Date(i.startAt));map.set(k,[...(map.get(k)||[]),i])});return map},[visible]);
  const selectedItems=grouped.get(selected)||[];
  async function create(){if(!form.title.trim())return;setSaving(true);const local=`${form.date}T${form.allDay?"00:00":form.time}:00`;const r=await fetch("/api/calendar/items",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,startAt:new Date(local).toISOString()})});const d=await r.json();setSaving(false);if(!r.ok)return toast.error(d.error||"Nu am putut salva.");setForm({...form,title:"",notes:""});setShowForm(false);setSelected(form.date);toast.success("Element adăugat în calendar.");router.refresh()}
  async function patch(id:string,data:Record<string,unknown>){const r=await fetch(`/api/calendar/items/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(!r.ok)return toast.error("Actualizarea a eșuat.");router.refresh()}
  async function remove(id:string){if(!confirm("Ștergi acest element din calendar?"))return;const r=await fetch(`/api/calendar/items/${id}`,{method:"DELETE"});if(!r.ok)return toast.error("Ștergerea a eșuat.");toast.success("Element șters.");router.refresh()}
  return <section className="space-y-4">
    <div className="rounded-2xl border border-ink-700 bg-ink-800 p-5 shadow-card">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><CalendarDays size={20} className="text-signal"/><h2 className="font-display text-lg font-semibold">Calendar intern al echipei</h2></div><p className="mt-1 text-sm text-mist-500">Notițe, taskuri, ședințe și deadline-uri comune.</p></div><button onClick={()=>{setForm({...form,date:selected});setShowForm(v=>!v)}} className="inline-flex items-center gap-2 rounded-xl bg-signal px-4 py-2 text-sm font-semibold text-white hover:bg-signal-bright"><Plus size={16}/>Adaugă</button></div>
      <div className="mt-4 flex flex-wrap gap-2">{[["OPEN","Deschise"],["ALL","Toate"],["NOTE","Notițe"],["TASK","Taskuri"],["MEETING","Ședințe"],["DEADLINE","Deadline-uri"]].map(([v,l])=><button key={v} onClick={()=>setFilter(v)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${filter===v?"bg-signal text-white":"bg-ink-900 text-mist-500 hover:text-mist-100"}`}>{l}</button>)}<button onClick={()=>setMine(v=>!v)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${mine?"bg-state-success text-white":"bg-ink-900 text-mist-500"}`}>Doar ale mele</button></div>
      {showForm&&<div className="mt-4 grid gap-3 rounded-xl border border-ink-700 bg-ink-900/40 p-4 sm:grid-cols-2 lg:grid-cols-4">
        <input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Titlu" className="input sm:col-span-2"/>
        <select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} className="input"><option value="NOTE">Notiță</option><option value="TASK">Task</option><option value="MEETING">Ședință</option><option value="DEADLINE">Deadline</option></select>
        <select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})} className="input"><option value="LOW">Prioritate mică</option><option value="MEDIUM">Prioritate medie</option><option value="HIGH">Prioritate mare</option></select>
        <input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className="input"/>
        <input type="time" disabled={form.allDay} value={form.time} onChange={e=>setForm({...form,time:e.target.value})} className="input"/>
        <select value={form.assigneeId} onChange={e=>setForm({...form,assigneeId:e.target.value})} className="input"><option value="">Fără responsabil</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select>
        <label className="flex items-center gap-2 text-sm text-mist-500"><input type="checkbox" checked={form.allDay} onChange={e=>setForm({...form,allDay:e.target.checked})}/>Toată ziua</label>
        <textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Notițe și detalii…" className="input min-h-20 sm:col-span-2 lg:col-span-3"/>
        <div className="flex items-end gap-2"><button onClick={create} disabled={saving||!form.title.trim()} className="rounded-lg bg-signal px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">{saving?"Se salvează…":"Salvează"}</button><button onClick={()=>setShowForm(false)} className="rounded-lg border border-ink-600 px-3 py-2 text-sm text-mist-500">Anulează</button></div>
      </div>}
    </div>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]">
      <div className="overflow-hidden rounded-2xl border border-ink-700 bg-ink-800 shadow-card"><div className="border-b border-ink-700 px-4 py-3 font-display font-semibold">{MONTHS[anchor.getMonth()]} {anchor.getFullYear()}</div><div className="grid grid-cols-7 border-b border-ink-700">{DAYS.map(d=><div key={d} className="p-2 text-center text-xs font-semibold text-mist-500">{d}</div>)}</div><div className="grid grid-cols-7">{monthDays(anchor).map(d=>{const k=key(d),items=grouped.get(k)||[],outside=d.getMonth()!==anchor.getMonth();return <button key={k} onClick={()=>setSelected(k)} className={`min-h-28 border-b border-r border-ink-700 p-2 text-left hover:bg-signal-soft ${outside?"bg-ink-900/40":""} ${selected===k?"ring-2 ring-inset ring-signal":""}`}><span className={`text-xs ${outside?"text-mist-700":"text-mist-300"}`}>{d.getDate()}</span><div className="mt-1 space-y-1">{items.slice(0,3).map(i=><div key={i.id} className={`truncate rounded border px-1.5 py-1 text-[10px] ${TYPE_COLORS[i.type]}`}>{i.priority==="HIGH"&&"! "}{i.title}</div>)}{items.length>3&&<div className="text-[10px] text-mist-500">+{items.length-3}</div>}</div></button>})}</div></div>
      <aside className="rounded-2xl border border-ink-700 bg-ink-800 p-4 shadow-card"><div className="mb-3 flex items-center justify-between"><h3 className="font-display font-semibold">{new Date(`${selected}T12:00`).toLocaleDateString("ro-RO",{day:"numeric",month:"long"})}</h3><button onClick={()=>{setForm({...form,date:selected});setShowForm(true)}} className="text-signal"><Plus size={17}/></button></div>{selectedItems.length===0?<p className="py-8 text-center text-sm text-mist-500">Nicio activitate internă.</p>:<div className="space-y-3">{selectedItems.map(i=><article key={i.id} className="rounded-xl border border-ink-700 bg-ink-900/40 p-3"><div className="flex items-start justify-between gap-2"><div><span className={`inline-flex rounded px-1.5 py-0.5 text-[10px] font-semibold ${TYPE_COLORS[i.type]}`}>{TYPE_LABELS[i.type]}</span><h4 className={`mt-1 text-sm font-semibold ${i.status==="DONE"?"line-through text-mist-500":"text-mist-100"}`}>{i.title}</h4></div><button onClick={()=>remove(i.id)} className="text-mist-700 hover:text-state-error"><Trash2 size={14}/></button></div>{i.notes&&<p className="mt-2 whitespace-pre-wrap text-xs text-mist-500"><FileText size={12} className="mr-1 inline"/>{i.notes}</p>}<div className="mt-2 space-y-1 text-[11px] text-mist-500"><div><Clock3 size={11} className="mr-1 inline"/>{i.allDay?"Toată ziua":new Date(i.startAt).toLocaleTimeString("ro-RO",{hour:"2-digit",minute:"2-digit"})}</div><div><Users size={11} className="mr-1 inline"/>{i.assignee?.name||"Fără responsabil"} · de {i.author.name}</div>{i.priority==="HIGH"&&<div className="text-state-error"><Flag size={11} className="mr-1 inline"/>Prioritate mare</div>}</div><div className="mt-3 flex gap-1">{i.status!=="IN_PROGRESS"&&i.status!=="DONE"&&<button onClick={()=>patch(i.id,{status:"IN_PROGRESS"})} className="rounded bg-ink-700 px-2 py-1 text-[10px] text-mist-500"><Circle size={10} className="mr-1 inline"/>În lucru</button>}{i.status!=="DONE"&&<button onClick={()=>patch(i.id,{status:"DONE"})} className="rounded bg-state-success/15 px-2 py-1 text-[10px] text-state-success"><CheckCircle2 size={10} className="mr-1 inline"/>Finalizat</button>}{i.status==="DONE"&&<button onClick={()=>patch(i.id,{status:"TODO"})} className="rounded bg-ink-700 px-2 py-1 text-[10px] text-mist-500">Redeschide</button>}</div></article>)}</div>}</aside>
    </div>
  </section>
}